export const pics =[
  {
    imageUrl :"./images/QUENN.jpg",
    name : "Quenn",
    id :0,
    reason : "First, let me get you in my mood... This is my lock screen picture. It globally show you who i am !"
  },
  {imageUrl: "./images/at_the_cross.jpg",
   id:1,
   name : "at_the_cross",
   reason : "I had this picture first, for a while but i wanted something different, more joyful"},
  {imageUrl: "./images/blow_minds.jpg", 
   id:2,
   name : "blow_minds",
   reason : "I tried this but the picture was too small to fit the screen and i didn't want to stretch, i was ugly when stretched"},
  {imageUrl: "./images/from_rivers.jpg", 
   id:3,
   name : "from_rivers",
   reason : "I reallt like this one but the width doesn't like me too. It's too large so i can't have all the text on my screen"},
  {imageUrl: "./images/light_in_darkness.jpg",
   id:4,
   name : "light_in_darkness",
   reason : "This makes you feel like the light in darknes right ? Yeah but it's too small for the screen too. Sad ? Me too !"},
  {imageUrl: "./images/love_purple.jpg",
   id:5,
   name : "love_purple",
   reason : "Everything here describes me, don't you think so ? My favourite color (purple), the color of my soul (gold) but... I dare you to guest..."},
  {imageUrl: "./images/unamable.jpg",
   id:6,
   name : "unamable",
   reason : "I feel like i'm searching for my wadding dress and when i think i found it, it's blurry aaaarhg"},
  {imageUrl: "./images/love_purple.jpg",
   id:7,
   name : "love_purple",
   reason : "Everything here describes me, don't you think so ? My favourite color (purple), the color of my soul (gold) but... I dare you to guest..."},
  {imageUrl: "./images/unamable.jpg",
   id:8,
   name : "unamable",
   reason : "I feel like i'm searching for my wadding dress and when i think i found it, it's blurry aaaarhg"},
  ]